FROM mambaorg/micromamba:1.4.2 as builder

COPY docker-environment.yml .

RUN micromamba create --file docker-environment.yml

FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04

EXPOSE 8888

LABEL maintainer1.name="Sameerah Talafha"\
      maintainer1.email="sameerah@vectech.io"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Fix APT sources and install dependencies
RUN sed -i 's|archive.ubuntu.com|mirror.math.princeton.edu/pub/ubuntu|g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends curl make g++ git && \
    rm -rf /var/lib/apt/lists/*

# Ensure user 'meera' exists
RUN useradd -ms /bin/bash meera

# Copy Micromamba & Conda environment from builder stage
COPY --from=builder /opt/conda /opt/conda
COPY --from=builder /bin/micromamba /usr/bin/micromamba
COPY --from=builder /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh

# Set environment variables
ENV MAMBA_EXE=/usr/bin/micromamba
ENV CONDA_PREFIX=/opt/conda/envs/fastai-learner
ENV MAMBA_ROOT_PREFIX=/opt/conda/

# Copy application code
ADD . /home/meera/app

# Change ownership of the application directory
RUN chown -R meera:meera /home/meera/app

# Set working directory
WORKDIR /home/meera/app

# Switch to user meera
USER meera

# Ensure environment activation on shell startup
RUN echo 'source /usr/local/bin/_activate_current_env.sh' >> ~/.bashrc && \
    eval "$(micromamba shell hook shell=bash)" && \
    micromamba activate fastai-learner && \
    chmod +x docker-entrypoint.sh

EXPOSE 8888

ENTRYPOINT ["./docker-entrypoint.sh"]


