name: fastai-learner
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - fastai[all]
      - pytest
      - jupyterlab
      - matplotlib>=3.2.2
      - numpy>=1.18.5
      - opencv-python>=4.1.1
      - Pillow>=7.1.2
      - PyYAML>=5.3.1
      - requests>=2.23.0
      - scipy>=1.4.1
      - --extra-index-url https://download.pytorch.org/whl/cu116
      - torch==1.12.1+cu116
      - torchvision>=0.8.1
      - tqdm>=4.64.0
      - protobuf<=3.20.1
      - tensorboard>=2.4.1
